import Head from 'next/head';

export default function HeadPages() {
    return(
        <Head>
            <title>Charles Cantin</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1.0" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
    )
};